apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{name}"
spec:
  storageClassName: "{storageClassName}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{size}"

