### Must be applied at the target K8S cluster BEFORE the operator's docker runs.
# added per https://kopf.readthedocs.io/en/latest/walkthrough/resources/
# uses /v1 api, and the whole schema section is while the whole schema section is new
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ephemeralvolumeclaims.zalando.org
spec:
  scope: Namespaced
  group: zalando.org
  names:
    kind: EphemeralVolumeClaim
    plural: ephemeralvolumeclaims
    singular: ephemeralvolumeclaim
    shortNames:
      - evcs
      - evc
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true